import {useEffect, useRef, useState} from 'react';
import {api} from '../api/travel';
import {Icon} from './UI';
type WeatherData = {current: {time: string; temperature_2m: number; apparent_temperature: number; relative_humidity_2m: number; weather_code: number; wind_speed_10m: number}; daily: {time: string[]; temperature_2m_max: number[]; temperature_2m_min: number[]; precipitation_probability_max: number[]; sunrise: string[]; sunset: string[]; uv_index_max: number[]; weather_code: number[]}; hourly: {time: string[]; visibility: number[]}};
const cache = new Map<number, {data: WeatherData; at: number}>();
const pending = new Map<number, Promise<WeatherData>>();
function load(id: number) {const c=cache.get(id); if(c && Date.now()-c.at<900000) return Promise.resolve(c.data); if(!pending.has(id)) pending.set(id, api<WeatherData>(`/destinations/${id}/weather`).then(data=>{cache.set(id,{data,at:Date.now()});return data;}).finally(()=>pending.delete(id)));return pending.get(id)!;}
export function condition(code: number) {return code===0 ? ['Clear skies','sunny'] : code<4 ? ['Partly cloudy','partly_cloudy_day'] : code<50 ? ['Foggy','foggy'] : code<70 ? ['Rain expected','rainy'] : code<80 ? ['Snow','weather_snowy'] : code<95 ? ['Rain showers','rainy'] : ['Thunderstorms','thunderstorm'];}
export default function Weather({id, full=false}: {id: number; full?: boolean}) {
  const [data,setData]=useState<WeatherData>(); const [error,setError]=useState(false); const [retry,setRetry]=useState(0);const ref=useRef<HTMLDivElement>(null);
  useEffect(()=>{let alive=true;setData(undefined);setError(false);const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){observer.disconnect();load(id).then(d=>{if(alive)setData(d);}).catch(()=>{if(alive)setError(true);});}}, {rootMargin:'120px'});if(ref.current)observer.observe(ref.current);return()=>{alive=false;observer.disconnect();};},[id,retry]);
  if(!full)return <div ref={ref} className="weather-mini" title={error?'Live weather unavailable':data?`${condition(data.current.weather_code)[0]} · ${data.current.time} IST`:'Loading live weather'}><Icon name={data?condition(data.current.weather_code)[1]:'cloud'}/>{data?`${Math.round(data.current.temperature_2m)}°`:error?'—':'···'}</div>;
  return <div ref={ref} className="weather-panel"><div className="section-line"><h3>Out there, right now</h3><span className="eyebrow">Live weather</span></div>{error?<p>Weather is temporarily unavailable. <button className="text-button" onClick={()=>setRetry(r=>r+1)}>Try again</button></p>:!data?<p className="loading">Checking the skies…</p>:<><div className="weather-current"><Icon name={condition(data.current.weather_code)[1]}/><strong>{Math.round(data.current.temperature_2m)}°</strong><div>{condition(data.current.weather_code)[0]}<small>Feels like {Math.round(data.current.apparent_temperature)}°C</small></div></div><div className="weather-metrics"><span>Humidity <b>{data.current.relative_humidity_2m}%</b></span><span>Wind <b>{data.current.wind_speed_10m} km/h</b></span><span>Rain chance <b>{data.daily.precipitation_probability_max[0]}%</b></span><span>Sunrise <b>{data.daily.sunrise[0].split('T')[1]}</b></span><span>Sunset <b>{data.daily.sunset[0].split('T')[1]}</b></span><span>UV index <b>{data.daily.uv_index_max[0]}</b></span><span>Visibility <b>{((data.hourly.visibility[data.hourly.time.findIndex(t=>t.slice(0,13)===data.current.time.slice(0,13))]??data.hourly.visibility[0])/1000).toFixed(1)} km</b></span></div><p className="weather-advice"><Icon name="info"/>{data.current.weather_code>=95?'Thunderstorms forecast. Reconsider exposed outdoor plans.':data.daily.precipitation_probability_max[0]>50?'Rain is likely. Pack a rain jacket and check trail conditions.':data.daily.uv_index_max[0]>6?'Strong UV today. Bring sun protection for outdoor time.':data.daily.temperature_2m_min[0]<10?'Cool evenings ahead. Bring an extra layer.':'A good day to take it slow and explore.'}</p><div className="forecast">{data.daily.time.map((day,i)=><div key={day}><small>{i===0?'Today':new Date(day+'T12:00').toLocaleDateString('en',{weekday:'short'})}</small><Icon name={condition(data.daily.weather_code[i])[1]}/><b>{Math.round(data.daily.temperature_2m_max[i])}° <span>{Math.round(data.daily.temperature_2m_min[i])}°</span></b></div>)}</div><small>Updated {data.current.time.replace('T',' ')} IST · <a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open-Meteo</a></small></>}</div>;
}
