from sqlalchemy.orm import Session
from . import db, models

def seed_db():
    # Create tables
    models.Base.metadata.create_all(bind=db.engine)
    
    session: Session = next(db.get_db())
    if session.query(models.Place).first():
        print("Database already seeded.")
        return

    places_data = [
        {"name": "Bhangarh Fort", "state": "Rajasthan", "category": "heritage/folklore", "latitude": 27.0963, "longitude": 76.2863, "mood": "Mystery", "image_url": "https://upload.wikimedia.org/wikipedia/commons/4/43/Bhangarh_Fort_Entrance.jpg", "description": "17th-century fort ruins in Rajasthan, infamous for its haunted folklore and strictly prohibited entry after dusk."},
        {"name": "Kuldhara Village", "state": "Rajasthan", "category": "heritage/folklore", "latitude": 26.8735, "longitude": 70.7719, "mood": "Mystery", "image_url": "https://upload.wikimedia.org/wikipedia/commons/e/e6/Kuldhara_Village_Ruins.jpg", "description": "An abandoned village near Jaisalmer shrouded in local legends, deserted overnight by its inhabitants centuries ago."},
        {"name": "Jaisalmer Fort", "state": "Rajasthan", "category": "heritage", "latitude": 26.9124, "longitude": 70.9123, "mood": "Heritage", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Jaisalmer_Fort_2.jpg/800px-Jaisalmer_Fort_2.jpg", "description": "One of the few living forts in the world, glowing with golden sandstone architecture in the Thar Desert."},
        {"name": "Amer Fort", "state": "Rajasthan", "category": "heritage", "latitude": 26.9855, "longitude": 75.8513, "mood": "Heritage", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Amber_Fort_Jaipur_India.jpg/800px-Amber_Fort_Jaipur_India.jpg", "description": "Majestic hilltop fort featuring grand courtyards and intricate mirror work, perched high above Maota Lake."},
        {"name": "Rann of Kutch", "state": "Gujarat", "category": "landscape", "latitude": 23.7337, "longitude": 69.8597, "mood": "Solitude", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Great_Rann_of_Kutch.jpg/800px-Great_Rann_of_Kutch.jpg", "description": "A massive seasonal salt marsh in the Thar Desert that turns into a surreal white desert landscape."},
        {"name": "Diu", "state": "Daman and Diu", "category": "coastal", "latitude": 20.7144, "longitude": 70.9874, "mood": "Coastal", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Diu_Fort_04.jpg/800px-Diu_Fort_04.jpg", "description": "A coastal town blending serene beaches and Portuguese colonial architecture."},
        {"name": "Gir National Park", "state": "Gujarat", "category": "wildlife", "latitude": 21.1329, "longitude": 70.7923, "mood": "Wildlife", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Asiatic_Lion_in_Gir.jpg/800px-Asiatic_Lion_in_Gir.jpg", "description": "The last remaining refuge of the majestic Asiatic Lion, featuring dry deciduous forests."},
        {"name": "Udaipur", "state": "Rajasthan", "category": "lakes/heritage", "latitude": 24.5854, "longitude": 73.7125, "mood": "Heritage", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Lake_Pichola_Udaipur.jpg/800px-Lake_Pichola_Udaipur.jpg", "description": "Known as the City of Lakes, offering palatial architecture and breathtaking sunset views over Lake Pichola."},
        {"name": "Valley of Flowers", "state": "Uttarakhand", "category": "mountains/flowers", "latitude": 30.7280, "longitude": 79.6247, "mood": "Solitude", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Valley_of_Flowers_National_Park%2C_India.jpg/800px-Valley_of_Flowers_National_Park%2C_India.jpg", "description": "A high-altitude Himalayan valley bursting with endemic alpine flowers and rare wildlife."},
        {"name": "Jim Corbett National Park", "state": "Uttarakhand", "category": "wildlife", "latitude": 29.5300, "longitude": 78.7747, "mood": "Wildlife", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Bengal_tiger_%28Panthera_tigris_tigris%29.jpg/800px-Bengal_tiger_%28Panthera_tigris_tigris%29.jpg", "description": "India's oldest national park, famous for its Bengal tiger population and rich riverine landscapes."},
        {"name": "Rishikesh", "state": "Uttarakhand", "category": "adventure/spiritual", "latitude": 30.0869, "longitude": 78.2676, "mood": "Spiritual", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Rishikesh_Ghat.jpg/800px-Rishikesh_Ghat.jpg", "description": "The yoga capital of the world, sitting on the banks of the holy Ganges at the foothills of the Himalayas."},
        {"name": "Spiti Valley", "state": "Himachal Pradesh", "category": "mountains", "latitude": 32.2217, "longitude": 78.0322, "mood": "Solitude", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Key_Monastery%2C_Spiti_Valley.jpg/800px-Key_Monastery%2C_Spiti_Valley.jpg", "description": "A cold desert mountain valley featuring ancient monasteries and dramatic, barren landscapes."},
        {"name": "Tirthan Valley", "state": "Himachal Pradesh", "category": "nature", "latitude": 31.6360, "longitude": 77.3450, "mood": "Solitude", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Tirthan_Valley_HP.jpg/800px-Tirthan_Valley_HP.jpg", "description": "An offbeat Himalayan getaway beside the Tirthan River, acting as a gateway to the Great Himalayan National Park."},
        {"name": "Rohtang / Manali region", "state": "Himachal Pradesh", "category": "mountains", "latitude": 32.3716, "longitude": 77.2466, "mood": "Adventure", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Rohtang_Pass_View.jpg/800px-Rohtang_Pass_View.jpg", "description": "A high mountain pass offering thrilling road journeys, snow-capped peaks, and striking alpine views."},
        {"name": "Pangong Tso", "state": "Ladakh", "category": "lake", "latitude": 33.7595, "longitude": 78.6674, "mood": "Solitude", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Pangong_Lake_view.jpg/800px-Pangong_Lake_view.jpg", "description": "A stunning high-altitude lake known for its ever-changing hues of blue and dramatic mountain backdrop."},
        {"name": "Nubra Valley", "state": "Ladakh", "category": "landscape", "latitude": 34.6863, "longitude": 77.5673, "mood": "Adventure", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Hunder_Sand_Dunes.jpg/800px-Hunder_Sand_Dunes.jpg", "description": "A high-altitude cold desert featuring double-humped Bactrian camels and stark rocky mountains."},
        {"name": "Dzukou Valley", "state": "Nagaland", "category": "trekking/nature", "latitude": 25.5414, "longitude": 94.1030, "mood": "Solitude", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Dzukou_valley.jpg/800px-Dzukou_valley.jpg", "description": "Famous for its rolling green hillocks, seasonal flowers, and pristine, untouched trekking routes."},
        {"name": "Loktak Lake", "state": "Manipur", "category": "lake", "latitude": 24.5614, "longitude": 93.8197, "mood": "Solitude", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Loktak_lake_phumdis.jpg/800px-Loktak_lake_phumdis.jpg", "description": "The largest freshwater lake in Northeast India, famous for its floating circular swamps called phumdis."},
        {"name": "Kaziranga National Park", "state": "Assam", "category": "wildlife", "latitude": 26.5775, "longitude": 93.1711, "mood": "Wildlife", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/One_horned_rhinoceros_at_Kaziranga.jpg/800px-One_horned_rhinoceros_at_Kaziranga.jpg", "description": "A vast sanctuary hosting two-thirds of the world's great one-horned rhinoceroses among tall elephant grass."},
        {"name": "Living Root Bridges", "state": "Meghalaya", "category": "nature/heritage", "latitude": 25.2638, "longitude": 91.6853, "mood": "Nature", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Double_decker_root_bridge.jpg/800px-Double_decker_root_bridge.jpg", "description": "Incredible suspension bridges naturally formed by coaxing the roots of rubber fig trees across streams."},
        {"name": "Cherrapunji/Sohra", "state": "Meghalaya", "category": "waterfalls/nature", "latitude": 25.2702, "longitude": 91.7323, "mood": "Nature", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Nohkalikai_Falls_Cherrapunji.jpg/800px-Nohkalikai_Falls_Cherrapunji.jpg", "description": "One of the wettest places on Earth, renowned for its dramatic waterfalls and mist-covered landscapes."},
        {"name": "Mawlynnong", "state": "Meghalaya", "category": "village/nature", "latitude": 25.2023, "longitude": 91.9157, "mood": "Heritage", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Mawlynnong_village.jpg/800px-Mawlynnong_village.jpg", "description": "Famed as Asia's cleanest village, offering a pristine example of community-driven eco-tourism."},
        {"name": "Sundarbans", "state": "West Bengal", "category": "mangrove/wildlife", "latitude": 21.9497, "longitude": 89.1833, "mood": "Wildlife", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Sundarbans_Tiger_Reserve.jpg/800px-Sundarbans_Tiger_Reserve.jpg", "description": "The largest mangrove forest in the world and home to the elusive swimming Bengal tigers."},
        {"name": "Darjeeling", "state": "West Bengal", "category": "mountains/tea", "latitude": 27.0360, "longitude": 88.2627, "mood": "Heritage", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Darjeeling_Tea_Garden.jpg/800px-Darjeeling_Tea_Garden.jpg", "description": "A charming hill station known for its world-class tea estates and views of the mighty Kangchenjunga."},
        {"name": "Varanasi Ghats", "state": "Uttar Pradesh", "category": "heritage/spiritual", "latitude": 25.3176, "longitude": 83.0062, "mood": "Spiritual", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Varanasi_Ghats_Evening.jpg/800px-Varanasi_Ghats_Evening.jpg", "description": "One of the world's oldest continuously inhabited cities, lined with spiritual ghats leading into the Ganges."},
        {"name": "Agra / Taj Mahal", "state": "Uttar Pradesh", "category": "heritage", "latitude": 27.1751, "longitude": 78.0421, "mood": "Heritage", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Taj_Mahal_in_March_2004.jpg/800px-Taj_Mahal_in_March_2004.jpg", "description": "The iconic ivory-white marble mausoleum on the right bank of the river Yamuna, a universal symbol of love."},
        {"name": "Hampi", "state": "Karnataka", "category": "heritage", "latitude": 15.3350, "longitude": 76.4600, "mood": "Heritage", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Virupaksha_Temple_Hampi.jpg/800px-Virupaksha_Temple_Hampi.jpg", "description": "An ancient village filled with ruined temple complexes from the Vijayanagara Empire amidst a boulder-strewn landscape."},
        {"name": "Gokarna", "state": "Karnataka", "category": "coastal", "latitude": 14.5398, "longitude": 74.3168, "mood": "Coastal", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Om_Beach_Gokarna.jpg/800px-Om_Beach_Gokarna.jpg", "description": "A coastal pilgrimage town boasting pristine beaches and a much quieter vibe compared to its northern neighbor Goa."},
        {"name": "Coorg", "state": "Karnataka", "category": "hills/nature", "latitude": 12.3375, "longitude": 75.8069, "mood": "Nature", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Abbey_Falls_Coorg.jpg/800px-Abbey_Falls_Coorg.jpg", "description": "Known as the Scotland of India, characterized by sweeping coffee plantations, misty hills, and lush greenery."},
        {"name": "Munnar", "state": "Kerala", "category": "hills/tea", "latitude": 10.0889, "longitude": 77.0595, "mood": "Nature", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Munnar_Tea_Estate.jpg/800px-Munnar_Tea_Estate.jpg", "description": "An idyllic hill station featuring seemingly endless expanses of emerald-green tea plantations."},
        {"name": "Varkala", "state": "Kerala", "category": "coastal", "latitude": 8.7379, "longitude": 76.7163, "mood": "Coastal", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Varkala_Cliff_Beach.jpg/800px-Varkala_Cliff_Beach.jpg", "description": "Unique coastal destination known for its striking red laterite cliffs towering over the Arabian Sea."},
        {"name": "Periyar Wildlife Sanctuary", "state": "Kerala", "category": "wildlife", "latitude": 9.4679, "longitude": 77.1415, "mood": "Wildlife", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Periyar_National_Park.jpg/800px-Periyar_National_Park.jpg", "description": "A protected area famous for its elephant and tiger reserve, centered around a scenic artificial lake."},
        {"name": "Goa beaches", "state": "Goa", "category": "coastal", "latitude": 15.2993, "longitude": 74.1240, "mood": "Coastal", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Palolem_Beach_Goa.jpg/800px-Palolem_Beach_Goa.jpg", "description": "World-famous coastlines offering everything from quiet, secluded coves to vibrant nightlife spots."},
        {"name": "Andaman Islands", "state": "Andaman and Nicobar Islands", "category": "coastal/nature", "latitude": 11.7656, "longitude": 92.6586, "mood": "Coastal", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Radhanagar_Beach_Havelock.jpg/800px-Radhanagar_Beach_Havelock.jpg", "description": "A remote archipelago featuring crystal clear turquoise waters, vibrant coral reefs, and pristine white sands."},
        {"name": "Konark Sun Temple", "state": "Odisha", "category": "heritage", "latitude": 19.8876, "longitude": 86.0945, "mood": "Heritage", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Konark_Sun_Temple_Wheel.jpg/800px-Konark_Sun_Temple_Wheel.jpg", "description": "A 13th-century architectural marvel shaped like a gigantic chariot with intricately carved stone wheels."},
        {"name": "Chilika Lake", "state": "Odisha", "category": "lake/wildlife", "latitude": 19.7289, "longitude": 85.3262, "mood": "Wildlife", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Chilika_Lake_Bird_Sanctuary.jpg/800px-Chilika_Lake_Bird_Sanctuary.jpg", "description": "Asia's largest brackish water lagoon, acting as a massive wintering ground for migratory birds."}
    ]

    for p in places_data:
        place = models.Place(**p)
        session.add(place)
    
    session.commit()
    print(f"Successfully seeded {len(places_data)} places.")

if __name__ == "__main__":
    seed_db()
